ApiBundle\Entity\Country:
    type: entity
    table: country
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
                comment: Идентификатор
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            unique: true
            length: 45
            options:
                fixed: false
                comment: Название
        code:
            type: string
            nullable: false
            unique: true
            length: 3
            options:
                fixed: false
                comment: 'Идентификационный код'
    lifecycleCallbacks: {  }